image: Ubuntu2204  # образ для сборки

stack: node 18  # окружение

environment:
  nodejs_version: "18"

branches:
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование

install:
  - yarn install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn run build   # команда сборки
  
deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name UdavUPS
  - git config --global user.email wwwpashacrut@mail.ru
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"